version: '3.7'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-dev-pass
      POSTGRES_DB: development_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nodeapi:
    container_name: nodeapi-dev
    build:
      context: .
      dockerfile: ./dockerfile
    command: yarn dev
    depends_on:
      - postgresdb
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_USER: postgres-user
      DB_PASSWORD: postgres-dev-pass
      DB_DATABASE: development_db
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3333:3333

volumes:
  node_modules:
  postgres_data:
